dataset:
  root_dir: ./datasets/training
  root_eval_dir: ./datasets/eval
  root_test_dir: ./datasets/test
  env_id: 0
  env_id_test: 0
  
  # Eval split for client
  test_split: 0.9
  batch_size: 32
  num_workers: 4
  num_workers_server: 32
  # FLWR specific configs
  enable_live_eval: false
  # Number of episodes to run in the live simulator
  num_episodes_live: 5
  # List of Indexes of the environment to use for testing
  # test_env_idx_range: [400, 450]
  test_env_idx_range: [400, 401]
  # Indexes of the environments to use for testing in the live simulator
  test_live_idxs: [400]

  ############# EVALUATION PARAMS #############
  final_eval_env_idx_range: [400, 410] #[400, 410]
  # Indexes of the environments to use for testing in the live simulator
  final_eval_live_idxs: [400, 401, 402, 403, 404, 405, 406, 407, 408, 409]
  ############# TEST PARAMS #############
  final_test_env_idx_range: [410, 420] #[400, 410]
  # Indexes of the environments to use for testing in the live simulator
  final_test_live_idxs: [410, 411, 412, 413, 414, 415, 416, 417, 418, 419]
  
model:
  learning_rate: 0.001
  weight_decay: 1.0e-05
  epochs: -1
  optimizer: adam
constants:
  LEFT_SHOULDER_RGB_FOLDER: left_shoulder_rgb
  LEFT_SHOULDER_DEPTH_FOLDER: left_shoulder_depth
  LEFT_SHOULDER_MASK_FOLDER: left_shoulder_mask
  FRONT_RGB_FOLDER: front_rgb
  FRONT_DEPTH_FOLDER: front_depth
  FRONT_MASK_FOLDER: front_mask
  IMAGE_FORMAT: '{:06d}.png'
  LOW_DIM_PICKLE: low_dim_obs.pkl
transform:
  normalize_mean:
  - 0.5
  - 0.5
  - 0.5
  normalize_std:
  - 0.5
  - 0.5
  - 0.5
  action_min:
  - -1.0
  - -1.0
  - -1.0
  - -1.0
  - -1.0
  - -1.0
  - -1.0
  - 0.0
  action_max:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
video:
  path: /home/omniverse/Workspace/elsa_robotic_manipulation/elsa_robotic_manipulation/videos
wandb:
  project: BCPolicy-Training
  video_fps: 20
  video_format: gif
paths:
  val_ckpt: /home/omniverse/Workspace/elsa_robotic_manipulation/elsa_robotic_manipulation/ckpt/val
  reward_ckpt: /home/omniverse/Workspace/elsa_robotic_manipulation/elsa_robotic_manipulation/ckpt/reward
